# Generated by Django 3.0.6 on 2020-05-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='IMAGE',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
